# Generated by Django 4.2.7 on 2025-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='foods.foods'),
        ),
    ]
