# Generated by Django 4.2.7 on 2025-11-10 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foods_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='foods',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='foods.foods'),
        ),
    ]
