# Generated by Django 4.2.7 on 2025-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_wishlist_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='/food.jpg', upload_to='foods/'),
        ),
    ]
