# Generated by Django 4.2.7 on 2025-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_wishlist_foods_wishlist_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='foods.foods'),
        ),
    ]
