# Generated by Django 4.2.7 on 2025-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_foods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='food.jpg', upload_to='foods/media'),
        ),
    ]
